[theme]
primaryColor = "#627EEA"                # Ethereum blue
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F9FC"
textColor = "#0F172A"
font = "sans serif"

[server]
maxUploadSize = 200

[browser]
gatherUsageStats = false