[theme]
primaryColor = "#3B82F6"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F8FA"
textColor = "#0F172A"
font = "sans serif"

[server]
maxUploadSize = 200

[browser]
gatherUsageStats = false